### ISSUE TITLE
checksum of lua-dkjson version 2.5 under dunfell branch changed

### ISSUE THREAD

**Issue by oz-rw** [chris2511/meta-luarocks#4]
`recipes-luarocks/lua-dkjson/lua-dkjson_2.5.bb`:
> SRC_URI = "http://dkolf.de/src/dkjson-lua.fsl/tarball/dkjson-${PV}.tar.gz"
> SRC_URI[sha256sum] = "b469e80daa9f2355c675d9293e831f3f69153e49856c59634db97899121a720d"

Currently the sha256sum of the downloaded `dkjson-2.5.tar.gz` from [http://dkolf.de/src/dkjson-lua.fsl/tarball/dkjson-2.5.tar.gz](http://dkolf.de/src/dkjson-lua.fsl/tarball/dkjson-2.5.tar.gz) is `10ef6f0de7784cb692a169dccb6d2be63ffcdf40bc54c160591363f67f27b863` which results in an error during bitbake build.

**Comment by chris2511** [comment]
Updated dkjson in `dunfell` to 2.6
